### ISSUE TITLE
After every update generator settings and mqtt settings are wiped

### ISSUE THREAD

**Issue by Daniel-dev22** [jgyates/genmon#1099]
### Steps to Reproduce

Update genmon.
Check generator settings for propane tank size and find it's unset.
Mqtt settings are wiped and the genmqtt file is reset to default settings and no longer contains my configuration I added via the UI.

### Expected Result

Everything would work smoothly.

### Actual Result

Propane tank setting is lost.
Mqtt configuration is lost.

### Version Info

V1.19.02

**Comment by jgyates** [comment]
A few questions:
Did you run the follow the install procedure and run install script when you installed genmon? 

How are you updating genmon?

Are you saving your settings on the Settings and Add on page? If you are, do you setting get saved after you click "Save" and then refresh your browser?

What operating system are you running?

I assume you do not have email setup (otherwise you could submit your logs on the about page). Let's lookt at your log files.

what is the contents of the /var/log/genserv.log file?
what is the contents of the /var/log/genloader.log file?
what is the contents of the /var/log/genmon.log file?

**Comment by jgyates** [comment]
This is the instructions for installing gemon:

https://github.com/jgyates/genmon/wiki/3.3--Setup-genmon-software

Did you follow this procedure?

**Comment by jgyates** [comment]
Another question:

How are your starting genmon? Are you using the provided script (startgenmon.sh)?

**Comment by jgyates** [comment]
The genloader.log file message about the config files not being present occurs when you do not run the install script. Genmon expects the contents of the ~./genmon/conf file to be copied to /etc/genmon. If it does not find it there then it will copy it to that location. Genmon also expects that /etc/genmon is writable by the root user and persists. The contents of the ~/genmon/conf folder are updated along with the rest of the ~./genmon folder when you perform a software update.

your compose file has this line:

   /docker_container_volumes/genmon/conf:/etc/genmon

Does this map the ~./genmon/conf file to /etc/genmon?

If it does then that is your issue. The ~./genmon/conf file is not intended to be modified from the ~./genmon/conf folder as this folder will get updated every time you refresh the repository by updating the software. All of the conf files in ~./genmon/conf are copied to  /etc/genmon during the install or load process. Your docker image must have a writeable /etc/genmon folder and it must be persistent.

This link shows past issues threads with people running gemon in a docker or vm. These threads have some link to working docker configuration files: 

https://github.com/jgyates/genmon/issues?q=label%3A%22docker+or+vm%22+
