### ISSUE TITLE
Estimated Fuel Guage Increasing Instead of Decreasing.

### ISSUE THREAD

**Issue by bbenton1341** [jgyates/genmon#1180]
### Steps to Reproduce

Set Fuel Type to Propane.
Set Fuel Tank Size to 400.
Monitor Estimated Fuel Gauge before and after a generator run.

### Expected Result

Gauge decreases estimated fuel remaining

### Actual Result

Gauge increases estimated fuel remaining

### Version Info

Version V1.19.04
Several previous versions also exhibited this behavior.

### Logs

Yes
[genmon_logs.tar.gz](https://github.com/user-attachments/files/17016965/genmon_logs.tar.gz)

Model : RG03224ANAX
    Generator Serial Number : 3013603937
    Controller Detected : Evolution, Liquid Cooled
    Nominal RPM : 1800
    Rated kW : 32 kW
    Nominal Frequency : 60 Hz
    Fuel Type : Propane
    Generator Phase : 1
    Engine Displacement : 2.4 L
    Estimated Fuel In Tank : 401.47 gal
    Hours of Fuel Remaining (Estimated 0.50 Load ) : 235.29 h
    kW Hours in last 30 days : 0.45 kWh
    Fuel Consumption in last 30 days : -0.15 gal
    Total Power Log Fuel Consumption : -1.47 gal
    Run Hours in last 30 days : 0.70 h
    Run Hours in the last year : 6.66 h
    Fuel Level State : OK

**Comment by bbenton1341** [comment]
Generator Model:  Generac 32KV Liquid Cooled.

Maintenance :
    Model : RG03224ANAX
    Generator Serial Number : 3013603937
    Controller Detected : Evolution, Liquid Cooled

**Comment by bbenton1341** [comment]
I have followed the Appendix H page.  

I reset power log and fuel estimates.

Verified Fuel Tank size still set to 400 Gal.

Verified Fuel Gauge was reset to 400.

Started Generator and allowed to run a few minutes.

While it was running I see the Fuel Guage steadily increasing (not decreasing as it should), as shown below.

 

I am running Linux Logging add-on.  No others.

I will attach my kwlog.txt.

And I’ll submit registers momentarily.

 

Thank you!

**Comment by bbenton1341** [comment]
I have followed the Appendix H page.
I reset power log and fuel estimates.
Verified Fuel Tank size still set to 400 Gal.
Verified Fuel Gauge was reset to 400.
Started Generator and allowed to run a few minutes.
While it was running I see the Fuel Guage steadily increasing (not decreasing as it should), as shown below.

I am running Linux Logging add-on.  No others.
kwlog.txt and screenshots attached, and registers submitted via the about page.

Thank you!

![Genmon Settings for Fuel Type and Tank Size - Benton](https://github.com/user-attachments/assets/11a3e2ac-07da-4921-baf2-78c03c6a2c14)
![Genmon Status Page - Benton](https://github.com/user-attachments/assets/16e97248-2e27-4553-9078-8f4f04f76d76)
[kwlog.txt](https://github.com/user-attachments/files/17035318/kwlog.txt)

**Comment by jgyates** [comment]
Thanks for the info. I can duplicate the issue. Currently this looks like and issue specific to Liquid Cooled Propane units. I will keep you posted.

**Comment by jgyates** [comment]
I checked in an update that should correct the increasing fuel value. I had copied down a value from the 32kw spec wrong so instead of copying down fuel useage for 25%, 50% 75% and 100% I copied down the values for the exercise cycle, 25%, 50% and 75%. This caused the fuel consumption calculation to create fuel usages less and zero and the code did not check for negative values. I added the check and corrected the wrong value for the Evolution 32kW Propane fuel usage numbers.

All you should have to do is update from the about page. The version number has not changed.

Also note that the Evolution Liquid cooled models use a Hall Effect sensor to calculate current use so [this note](https://github.com/jgyates/genmon/wiki/Appendix-D-Known-Issues#5-current-and-power-output-values) may be of use if your numbers are off by an order of magnitude. You can tune to calculation if your Hall Effect sensor is not calibrated properly per the provided link.

Let me know how it goes for you. I am going to close this thread but feel free to post here with any follow up or questions.

**Comment by bbenton1341** [comment]
Thank you!  I updated, and the Fuel Remaining now shows below 400.  I’ll consider this resolved.

 

Bob Benton
