### ISSUE TITLE
No Generator Data

### ISSUE THREAD

**Issue by mattm55** [jgyates/genmon#137]
Use the template below if you have an issue or want to report a bug. If you have a question or a feature request you can ignore the questions below.

### Expected Behavior
~Able to read data from generator.

### Actual Behavior
~No data received from generator

### Steps to Reproduce (including precondition)

~Connected to generator with 7/8 pins and Raspberry PI 3 

### Screenshot on This Problem (if possible)
~n/a

### Your Environment

- Generator Model: 11kw - 7032
- Generator Registers: {Please write here}
- Genmon Version: latest available as of 6/15/2018

OK. I built 2 versions of the Raspberry Pi using RS232>TTL chip and the serial DB9 RS232 to TTL connectors and I'm not received data from the generator. Basically the same as the other thread but didn't want to hijack the thread and capture the diagnosis for future use.

Using the Raspberry Pi 3 b+ and a updated copy of Raspbian Stretch and loaded Genmon from the auto install. All works good in the web interface and config w/permissions. 

Power : 5v from gen's battery to usb.
Using GPIO pins Gnd, GPIO14 & GPIO15 with 3.3v (pin1)
USB Wireless adapter with extended range antenae
Manufacturer | Detroit DIY Electronics B00H95C0A2 6465800

Swapping the TX/RX results in no differences in receiving data and logs say no data received.
Loop back tests all the way to the 8 pin molex look good.

Question 1: Is there a possibility that the dealer/installer turned off output to Port 1?
Question 2: Conflict with the USB wireless adapter?  I have another model coming in case this is a conflict.

This is a great project so I'm willing to add my experiences getting the generator monitored and moving forward.
Thanks, Matt

**Comment by jgyates** [comment]
Hi Matt,

Regarding your 2 questions:
1) I don't think that is possible. The dealer menus in the Evolution and Nexus controller do not offer an option to disable the port. There is no reference to this in the diagnostic manual or by viewing the dealer menu directly so this leads me to this conclusion.
2) I doubt that is the case. If you network is working then that portion of it should be OK.

If you have validated that you have the correct pins on the molex and tried reversing them (depending if you have a DTE or DCE serial connector), then I would look at your ground connection. How are you powering your pi? If your ground connection is not secure your pi will likely still function, but your will not be able to communicate since your voltage on the pi and the controller will have a different ground reference.

If you have a multimeter you can do a quick test to validate your ground by measuring continuity between the pi ground and the negative battery or your generator chassis.

A photo of your wiring may help also.

**Comment by mattm55** [comment]
OK. Let me snap some pics to make sure we verify connections when I get home today. Loopback tests all the way to the molex work fine however.

Yes, I'm powering up using the 5v Gen battery to USB module in the hardware listed. I didn't want to have under voltage issues with the RP3 b+ and USB wifi with extender. I will verify the common ground as I do have a multi-meter. I will also verify I have 5v's/Gnd coming out of the Gen pin 1 &2 to make sure that the port is active. My sanity check.

More to follow and thanks for the hints to check.

Matt

**Comment by mattm55** [comment]
So I've attached my hardware and wiring images. The four wires are 3.3v, GND, RX and TX. Power is from the 5v battery USB. I'll test the 8 pin port on the gen for GND and make sure I get 5v's as the sanity check.

![p1000988](https://user-images.githubusercontent.com/1926818/41693005-4e123aee-74d1-11e8-8b59-f650465e1983.JPG)
![p1000989](https://user-images.githubusercontent.com/1926818/41693011-533fdc1a-74d1-11e8-8fbd-3bd0394e2f3e.JPG)
![p1000985](https://user-images.githubusercontent.com/1926818/41693019-5e5a01c0-74d1-11e8-8a9c-2492dd95fe93.JPG)

**Comment by mattm55** [comment]
Closed by mistake. Sorry.

**Comment by jgyates** [comment]
Nothing is jumping out at me as incorrect from your pictures. However, since you are only running 2 wires to the molex connector, your ground connection on the battery must make a good contact or you will not be able to communicate. I would either use a multimeter to measure continuity between the battery ground terminal and the pi or add the ground connection from the molex to the #5 position (GND) on the green terminal screw.

Corrosion can build up on the battery terminals and just because it appears to be touching does not mean that you have a good connection.

**Comment by mattm55** [comment]
OK. It was my mistake. I verified the 8 pin molex with 5v and ground and realized I was off on pins 1 thru 8. Duh. 

After making corrections, I have the gen connected. :o)

Thanks. Matt

**Comment by jgyates** [comment]
Thats a good way to verify the pinout is correct. I will make a note on the wiki about that.
