### ISSUE TITLE
LTE Connectivity?

### ISSUE THREAD

**Issue by Blast** [jgyates/genmon#163]
Has anyone tried to setup LTE Connectivity for when the internet is down to send you text messages?

Seeed Studio has this module:  https://www.seeedstudio.com/LTE-Cat-1-Pi-HAT-%28USA-AT%26T%29-p-3056.html

**Comment by jgyates** [comment]
I do not know of anyone trying this approach, however from the software's perspective, the app uses the any available TCP/IP network device to communicate.  The OS desiginates one device as primary and this one will be used first for email. Any network device can be used for the web interface. As long as a secondary device has a route to the internet, if the primary is not available, then Linux will use the secondary. I have validated this behavior with WiFi and Ethernet. 

I have not used this LTE HAT before, but as long as the power consumption is reasonable it should work (assuming you have a LTE provider, signal,  and assuming the device shows up as a network device with a valid IP). If you use any USB devices or are powering from the molex connected (instead of the battery), the HAT along with the power consumed by the USB ***may*** be greater than the pi can provide (the powering over molex appears to supply less current based on empirical evidence).

**Comment by Blast** [comment]
If I send you a HAT, would you consider integrating it?

**Comment by jgyates** [comment]
Sure, you can send me an email (generatormonitor.software@gmail.com) and I will send you my address.

**Comment by jgyates** [comment]
You can now send text messages over LTE or GSM with [this](http://wiki.seeedstudio.com/LTE_Cat_1_Pi_HAT/) adapter. 

I structured the code where it is possible to make other cards work with little effort.

Details on the setup are here:

https://github.com/jgyates/genmon/wiki/1----Software-Overview#gensms_modempy-optional


***Note*** the LTE Hat card uses the pi on board serial port so genmon will need to use a USB serial port.

Let me know if there are any questions.

**Comment by jgyates** [comment]
I forgot to mention: The modem requires one program to be installed. I added this to the documentation on gensms_modem.py:

***NOTE***: To use the modem you must install the rpirtscts program located [here](https://github.com/mholling/rpirtscts). This program source files must be downloaded and built however the process is straightforward and is described on the rpirtscts project page.
