### ISSUE TITLE
wifi extension cable question

### ISSUE THREAD

**Issue by ts4s** [jgyates/genmon#197]
Does anyone know the name to the wifi extension cable being used in the attached photo?
![inside enclosure](https://user-images.githubusercontent.com/1710792/47222025-67c1ea80-d37b-11e8-9b14-6d88f2e447a7.jpg)

Tried to find the original thread with it to see if it is listed. Anyways, I'm looking to do the same with my wifi connection. Currently I have a usb extension cable hanging out of my generator, so the wifi module is expose to the weather. Really want to fix this before winter sets in.

I'm thinking it's this but not sure on the connectors:
https://www.amazon.com/dp/B07DLSQQFW/ref=sspa_dk_hqp_detail_aax_0?psc=1

Thanks!

**Comment by jgyates** [comment]
The connectors are called SMA connectors. I got these and an external antenna at www.data-alliance.net

https://www.data-alliance.net/sma-extension-cables-4-inch-to-6-feet/

There are a few variations of connectors 

RP-SMA - reverse polarity SMA
NP-SMA - normal polarity SMA

Both come in male and female varieties.

https://en.wikipedia.org/wiki/SMA_connector

It has been a while since I was using the antenna (switched to Ethernet) so I don't remember the exact one I used. If you use the RP and need the NP then your antenna will basically do nothing for you as the ground and signal will be reversed.

**Comment by ts4s** [comment]
cool, so I should be fine with the normal polarity sma... Thank jgyates!

**Comment by jgyates** [comment]
possibly, I dont remember if the wifi adapter is NP or RP. You could just get both cables (I think they are inexpensive) and try each one.

**Comment by ts4s** [comment]
just completed my order with data-alliance, good prices and reasonable ship cost :-)

**Comment by lmamakos** [comment]
The [USB WiFi dongle ](https://cgi.ebay.com/ws/eBayISAPI.dll?ViewItemVersion&item=311736220053&view=all&tid=855824660021) that I used had an RP-SMA connector arrangement.  I think for Wi-Fi products, the RP-SMA variation is most commonly seen due to the fiction that such an uncommon connector would make it "impossible" for the end-user to use a different antenna than the one that the FCC Part 15 device was tested against.  Which is pretty funny these days, because trying to find an normal SMA jumper (like for your GPS antenna or similar) is more difficult than the RP variation.

**Comment by ts4s** [comment]
the RP-SMA connector is what I needed for my setup. I was able to get it install and clean up my setup. 

![img_3218](https://user-images.githubusercontent.com/1710792/47611703-9190a680-da38-11e8-83e7-7ccfc3aa5001.jpg) Outside Antenna view
![img_3219](https://user-images.githubusercontent.com/1710792/47611704-9190a680-da38-11e8-8944-082d36e7b1fe.jpeg) Inside Antenna View
![img_3217](https://user-images.githubusercontent.com/1710792/47611702-90f81000-da38-11e8-97d9-f032f1a44806.jpg) Pi view
![img_3220](https://user-images.githubusercontent.com/1710792/47611706-92293d00-da38-11e8-87c9-03818622f8d1.jpg) Command strips work great for holding the Pi.

**Comment by jgyates** [comment]
Thanks for the pics!
