### ISSUE TITLE
genpushover error when Utility Service is Down

### ISSUE THREAD

**Issue by tobiwankenobi17** [jgyates/genmon#203]
Hello everyone.
Last weekend I had two short power outages.  I received notification for "Utility Service is Up", but not for "Utility Service is Down".

### Expected Behavior
During a power outage, I would expect to get a Pushover notification that the power is out.
I tried to troubleshoot this myself, but haven't quite figured out how the python scripts interact.
In the genpushover.py, I found:
```
#----------  OnUtilityChange ---------------------------------------------------
def OnUtilityChange(Active):

    if Active:
        console.info("Utility Service is Down")
        SendNotice("Utility Service is Down")
    else:
        SendNotice("Utility Service is Up")
        console.info("Utility Service is Up")
```
Since the SendNotice for "Utility Service is Up" worked, I'm not quite sure how to troubleshoot why it did not work for "Utility Service is Down".

### Actual Behavior
No notification through pushover.
(Outage Notice / Utility Power Out did come in through email though.)
> genpushover log:
> 2018-11-04 21:02:53,150 : Error: [Errno socket error] [Errno -3] Temporary failure in name resolution
> 2018-11-04 21:25:46,358 : Error: [Errno socket error] [Errno -3] Temporary failure in name resolution

### Steps to Reproduce (including precondition)
Pushover is setup with genmon and on your phone.
Cut main power.

### Screenshot or Pictures relating to the problem (if possible)
The picture shows that only the power recovered, but not the power lost triggered a Pushover notification.
![image](https://user-images.githubusercontent.com/44825641/48108468-39645c00-e211-11e8-8361-4be496040e6f.png)

### Your Environment

- Generator Model: Evolution, Air Cooled
- Generator Registers: Sorry, don't quite know how this works.
- Genmon Version: V1.11.19

Please let me know if I didn't follow any guidelines.  This is my first post.

**Comment by jgyates** [comment]
@tobiwankenobi17 

Based on the info you posted, my best guess at the cause of your problem is this: The program genpushover.py calls the python library for the pushover service at pushover.net. This call into the pushover library is generating the error in your logs (Temporary failure in name resolution). My guess is that some component on your network (router, wifi equipment, switch or ISP modem) is not connected to a uninterruptible power supply (UPS). If this is the case, then the temporary interruption in your internet / network is likely causing the URL used by the pushover library not to be resolved to an IP address so the pushover call for power outage is interrupted. In other words, the pi can not access your DNS server at the time of your power outage because it can not get to the internet. If the to pushover fails it does not retry.

Let me know if this is not the case, but based on the info provided it does appear to fit the data.

**Comment by lmamakos** [comment]
In my personal situation, upon power outage, my cable ISP goes down pretty much immediately since they apparently have no battery backup in the power supplies for their trunk amplifiers.  Despite having all my stuff on UPS (plus the generator!) I'm still screwed in that regard.   Those green power injectors hung on poles every so often to run the amplifiers are supposed to have some lead-acid batteries in them, but they don't (or haven't been replaced in years) so no power, no ISP service.

I'm thinking of adding an LTE cellular modem and perhaps use that for SMS or other notification purposes.  But my mobile coverage options are terrible.  I have an LTE Network Extender (that's an RF repeater, essentially) that's required to be working for my phones to have cellular coverage.  Maybe an LTE modem with external antenna in just the right spot on the generator outside would solve this problem..

**Comment by tobiwankenobi17** [comment]
@jgyates 
Thanks for the quick reply.
I'm powering the Pi from the generator's battery.  My cable modem and router is on a UPS.  I couldn't figure out where in my setup I could possible cut the power.
I unplugged the UPS -- and internet down.
I recently added a second router as a backup.  I forgot to power the hub between the cable modem and the routers through the UPS.  **Doh!**

I think that was the issue.
Of cause it is possible that the ISP would lose power as well, but that is outside of my control.

Thanks again for the response.
And thanks a ton for making genmon available to everyone.

I haven't performed a full test (i.e. cut power), but this seems to have been the issue.  From my perspective, this tracker can be closed.
