### ISSUE TITLE
Hitting a wall on the serial end, hoping for help.

### ISSUE THREAD

**Issue by nah2323** [jgyates/genmon#212]
Can anyone vnc into my RPi to run a serial test?  I’m hitting a wall for more than a week, and I’m sure the cable is made correctly.  Can post pics. 

Tia!

**Comment by liltux** [comment]
@nah2323, I doubt anyone would be any useful to vnc into your pi.  But, pictures and description of your cable, ttl to 232 adapter, and pi connections would be extremely useful.  Are you having issues running the command "serialtest.py"?  or you are getting bad results each time?  have you ran the "serialconfig.py -e" option to set everything up?  Also try running "serialconfig.py -c", this will tell you if everything on the pi side is configured correctly for the onboard serial device.

**Comment by jgyates** [comment]
I agree with @liltux , pics would help a lot. Also, I am assuming you looked at this page as it was designed to take you thought the serial trouble shooting process.

https://github.com/jgyates/genmon/wiki/3.6---Serial-Troubleshooting

**Comment by nah2323** [comment]
Hey gents, yes I used the wiki to do most of it, but python isn’t doing much to help me with the serial test.  I have python3 but I can’t get serial test to do anything.  I keep getting errors

**Comment by jgyates** [comment]
@nah2323 

The raspbian operating system has both python2 and python3 installed and defaults to version 2. The default version is just a symbolic link that points to an actual binary.

    /usr/bin/python    - symbolic link to eithert /usr/bin/python2 or /usr/bin/python3
   /usr/bin/python2   - symbolic link to the python 2.x binary, usually /usr/bin/python2.7
   /usr/bin/python3 - symbolic link to the python 3.x binary, usually /usr/bin/python3.5 

You can tell the default version by typing:

     python -V

you can also run python2 or python3 manually by using the python2 or python3 instead of python on the command line:

      sudo python2 serialtest.py 

The question that I have is this: Is python3 the default on your system. This is not the default for the operating system and changing the symbolic link could break other things. If you type python -V from the console what is the output?

**Comment by liltux** [comment]
What @jgyates said, and can you copy paste your errors as well.  Are you using raspberry pi and raspbian? Or a different version like orangepi or other variants with slightly different operating system?

**Comment by jgyates** [comment]
FYI, I checked in an update that should be more friendly to python3. I have tested this modestly with python3.5. To update your software to the latest, form the genmon directory type:

     sudo bash ./genmonmaint.sh update 

While this may get you past the serialtest.py and ser

**Comment by jgyates** [comment]
@nah2323 

Any update on your status?

**Comment by nah2323** [comment]
Haven’t been able to update RPi yet, on vacation until Sunday.  Will try update and report back.
