### ISSUE TITLE
Alarm notifications not specific

### ISSUE THREAD

**Issue by jcherney** [jgyates/genmon#218]
Hi,

Received an alarm (email and text) this morning, showing as UNKNOWN. Upon logging into the system, the software was showing INSPECT AIR FILTER. I sent logs and registers to you just now- but it seems that the notifications don't (in this case) show the actual alarm problem.

**Comment by jgyates** [comment]
@jcherney 

This is expected behavior. The controller status register 0001 outputs unique values for various conditions (switch state, current alarm, etc). These contents of this register is not  documented by Generac. Alarm E-Codes are documented by Generac and are used by the alarm a log (the software stores these in ALARMS.txt).  The software can only know the values of all of the conditions or register 0001 based on user feedback, which you are providing. I have updated the code 00000010 to correspond to Inspect Air Filter (V1.12.0). 

More info on this topic is here: 
https://github.com/jgyates/genmon/wiki/Appendix-4-Known-Issues
https://github.com/jgyates/genmon/issues/13
