### ISSUE TITLE
Wifi Mobile Link question

### ISSUE THREAD

**Issue by rnyoakum** [jgyates/genmon#337]
I have a new Guardian 22KW G0070432 with the Evolution 2 controller and built-in WiFi.  It currently communicates to Generac via their Mobile Link service using the built-in Wifi which is connected to my home WiFi network and the Internet.  The Mobile Link service connection appears to be over the Internet.  

You have a very nice controller and monitor.  Do you believe it would be possible for the generator to be connected over the built-in WiFi to both your controller system and Mobile Link service at the same time?  I doubt that it is easy to leave and rejoin the Mobile Link service and doing so would likely confuse the Mobile Link service reporting.  

Would your controller connect directly to the Generator’s WiFi or to my home WiFI network and the Generator’s IP address assigned on my home network?  Do you believe the Evolution 2 supports two simultaneous connections and interaction over its built-in WiFi?

**Comment by jgyates** [comment]
This project connects a raspberry pi to the generator via serial connection, then the raspberry pi connects to you home network. Using this software and MobileLink at the same time is possible (see this thread https://github.com/jgyates/genmon/issues/334), however it will require you to modify the cable connecting the mobile link and your generator to allow the pi to connect to the generator as well. The link above references how to search all issues for "Evolution 2.0" related articles, or you can click this link:

https://github.com/jgyates/genmon/issues?utf8=%E2%9C%93&q=+label%3A%22Evolution+2.0%22+

Since this is a duplicate question I am closing this thread. If you have related questions you can post them to this thread.
