### ISSUE TITLE
22kw incorrectly listing Rated Max Power at 15kw

### ISSUE THREAD

**Issue by xjrguy** [jgyates/genmon#506]
Use the template below if you have an issue or want to report a bug. If you have a question or a feature request you can ignore the questions below. This is a template so feel free to remove any of this text. Try to include the info below when applicable.

***NOTE:*** If you are having issues with your serial connection, please read this page before posting:

https://github.com/jgyates/genmon/wiki/3.6---Serial-Troubleshooting

If you are having other issues, please see the following page:

https://github.com/jgyates/genmon/wiki/3.5---General-Troubleshooting

You can search past issues by removing the "is:open" keywords from the search window and adding any keywords that are relevant to your issue.

If you need to send you logs and registers to the developer, if your email is setup and working properly you can click send your logs on the About page in the web interface.

### Expected Behavior

22kw Rated Max Power should be 22kw (or more accurately 19.5kw running on natural gas)

### Actual Behavior

Rated max power is displayed as 15kw on the maintenance page and also incorrectly slewing Power Output status gauge on status page (home)

### Steps to Reproduce (including precondition)

View the status page and Power Output gauge is displayed incorrectly using 15kw as the baseline vs 22 and the maintenance page lists Rated Max Power as 15 instead of 22

### Screenshot or Pictures relating to the problem 
![B6FA63F9-010E-4F3E-A988-B7F30CB3724A](https://user-images.githubusercontent.com/79072582/107907461-a09d0a80-6f08-11eb-8728-355157907c05.jpeg)
![DDC35CF1-DC5A-437A-ADD4-37A86FA97523](https://user-images.githubusercontent.com/79072582/107907655-1a34f880-6f09-11eb-8c4d-fcd77c677d6e.png)

{Please write here}

### Your Environment

- Generator Model: G0070433
- Genmon Logs: Submit via the About page
- Genmon Version:  V1.15.19

**Comment by jgyates** [comment]
I would need to see your registers submitted on the about page to look into this.

**Comment by jgyates** [comment]
This should be fixed now. Not sure what is going on with the thread, but it is not showing up in the issues for me. Just update from the about page and it should be fixed once the software is updated/restarted.

**Comment by liltux** [comment]
Jason,
I think you alarm match with the Annunciator values is working as I can get
Estop alarm and Low coolant level.  Since this unit is not running I cannot
check all of them.  Just wanted to let you know.  Also, the alarm email
shows up before the page can update with the correct alarm type.  So the
data is on the webpage eventually, but that info is missing because it is
not processed or available when the email is sent.  Maybe a slight delay?
Just some info.  If you install VNC on the RPi you can access the webpage
view of the Powerzone at 192.168.100.219.

Jared VanFleet

[image: github.png] <https://github.com/liltux>[image: linkedin.png]
<http://www.linkedin.com/in/jared-vanfleet-523628100>[image: twitter.jfif]
<https://twitter.com/_liltux_?lang=en>
