### ISSUE TITLE
12V Battery Threshholds

### ISSUE THREAD

**Issue by TopBanana123** [jgyates/genmon#588]
I'm trying to learn if the red/yellow/green marks in the battery voltage chart have any significant meaning?

I plugged in my Genmon into my brand new Generac RG027 a few days ago and noticed battery voltage was 12.6v which seems low, its now 12.5v, but the needle is still in the green

I'm trying to figure out of my unit has a problem with the battery charger, or if it might kick on the charger once it gets into the yellow?

**Comment by jgyates** [comment]
Unless your getting errors in your Alarm log relate to battery problems I would not think you have an issue with your charger. The controller will log errors to the alarm log if it needs to charge too much due to undervoltage.

The colors on the battery gauge are fixed (for 12V batteries) with the green being between 12.5 and 15V. This range should be the acceptable range of the battery according to the maintenance manual. The controller handles all aspects of charging and there is not a lot of visibility to what is going on with the charger over modbus. The maintenance manual does have info on the basic operation of the charger.

**Comment by TopBanana123** [comment]
Thanks you guys,

I'll get out there tomorrow and measure the voltage. Its still at 12.5, so I'm not going to write it off to a problem just yet. I might delay my exercise on Sunday just so I can see what it does

**Comment by grsthegreat** [comment]
You can also start the unit 2 to 3 times to draw down battery. That should kick it into charging cycle. Unfortunately the easiest way to verify charging is thru dealer menu. But if you had dc voltage tester on battery while starting, you should see a jump when charger kicks in.
