### ISSUE TITLE
Ambient temperature measured 

### ISSUE THREAD

**Issue by grsthegreat** [jgyates/genmon#589]
I have an evolution 1 controller, and it reads ambient temperature thru a thermometer within the generator. This helps with the several parameters within the control system. I cannot see this reading within the genmon system. I am wondering if I’m just missing this?

**Comment by jgyates** [comment]
I have tried to find the ambient temp sensor value over modbus for Evo 1, however I have not found it to date. I have found it on Evo 2. the value exported on Evo 2 is the Fahrenheit value. The value exported on Evo 1 liquid cooled modes does inversely vary with the temperature but it is not an inverse linear correlation so that one is not as straightforward. To me, it looks like the ambient temp is not exported over modbus for Evo1, but if anyone has data I would be glad to take a look at it.
