### ISSUE TITLE
(Not an issue) Anyone have concerns with battery lifetime?

### ISSUE THREAD

**Issue by TopBanana123** [jgyates/genmon#626]
I used to have my Pi powered via PoE, and I noticed the battery charger would come on maybe once every 2 weeks (No MobileLink connected)

I noticed since switching to powering the Pi from the 12v battery as well as a fiber media converter, the battery charger comes on more often than not. Instead of every 2 weeks, most times I check, its on

Are my observations with the battery charger being on much more often in line with what you guys are seeing? I'm concerned that the battery sitting under higher voltage much more often is going to wear out the battery much sooner than it would ordinarily 

What do you guys think?

**Comment by jgyates** [comment]
Background: The battery charging status is only available to Evolution Liquid Cooled models.

I am sure the battery does charge more since the pi does draw power. I don't have any data on how often my charger is on (it is off now) however the comments here describe the methodology of the battery charger and may help shed some light. the charging cycle is quite long and there are some temperature specific variables in the charging method.

https://github.com/jgyates/genmon/blob/master/genmonlib/generac_evolution.py#L3518
