### ISSUE TITLE
Modbus Splitter?

### ISSUE THREAD

**Issue by gss2002** [jgyates/genmon#66]
Could you theoretically obtain a modbus rs485 splitter and have the Generac Mobile Link Remote Monitoring System and one using the method here to monitor locally? Just a thought?
https://www.icpdas-usa.com/documents/WhitePaper-Multiple-Modbus-RTU-Masters-Sharing-One-Slave.pdf or 

https://www.icpdas-usa.com/tsh_735.html

**Comment by jgyates** [comment]
Hi @gss2002,

Good question. 

Using the splitter you show in the link would be a problem due to the fact that the generator controller uses Modbus over RS-232, not RS-485, so electrically they are not compatible. In theory, if this product was RS-232 and the buffering described in the PDF work as advertised it would work. It looks like they have a RS-232 version:  https://www.icpdas-usa.com/tsh_722.html

Alternatively, if the goal is to use Mobile Link along with genmon, you could could achieve this if you used two RS-232 serial ports and made some modifications to the code. You would need to monitor what mobile link transmitted with the receive input of one of the serial ports and also monitor what the generator transmitted with the second serial port's receive input. This would require no buffering device. I initially used a scenario like this to get genmon up and running, but my goal was to replace my need to pay fees and improve the notification time, so I ended up migrating to a version that did not rely on Mobile Link. That early version had very limited functionality so there would still need to be quite a bit of code written  or ported to get the same functionality that genmon has now.

**Comment by gss2002** [comment]
Thanks for the fast response @jgyates when it warms up a bit I'll have to go out and play around a bit.  did he he TSH-722 which I may order and try out see what it does. Basically I'll build some custom cabling to attach to this product to support both. Basically it would be to use both mobilelink and genmon as my electrician is the one who wanted to be able to monitor the generator remotely which honestly is nice if I am away from home but for me being in IT it would be interesting to monitor the gen from one of my PIs or just run it on one my vmware machines running debian or ubuntu

**Comment by jgyates** [comment]
Hi @gss2002 

I am closing this issue now. Feel free to comment in this thread if you end up trying this approach and I will re-poen the thread.

Thanks
Jason

**Comment by cron410** [comment]
We have Generac H-100 panels in our generators and RS485 is attractive to our use case. I can switch the communication from RS232 to RS485 but I'm not sure if that would move the Modbus communication over to RS485 as well. Using RS485 would allow me to place the Pi indoors with the rest of the monitoring equipment.

**Comment by liltux** [comment]
@cron410, if you are using an annunciator panel then the generator h-panel is for sure set for master, it is the default.  The o ly way to change the h-panel 485 port to a slave is to have a service dealer with a security key to program the controller as a slave o. That port.  If using an annunciator, this will cause the annunciator to not work as it is a slave on that bus.

**Comment by cron410** [comment]
Can the genmon software act as a slave? The rs485 port is empty right now, look at the bottom of the picture
 http://imgur.com/a/NhN4QVd I'm not really sure what an annunciator is. I found references to PLCs and alarms on other sites. Does anyone have a link where i can learn more about 485 and the basics of making things communicate with it?

**Comment by jgyates** [comment]
@cron410 

No, the genmon software will only act as a master.

**Comment by bmg01907** [comment]
I'm using Genmon on a Generac model 0065510 22kW natural gas unit that has an Evolution 1.0 controller (firmware version 1.10; hardware version 1.05; purchased Dec. 2014).  It works great.  I'm planning to add an ICPDAS tSH-732i Port Sharer to connect two masters (Genmon and the Generac 6664 Wireless Local Monitor) to the generator.  Any thought on whether this will work?  Has anyone done this?

**Comment by jgyates** [comment]
I have not heard of anyone doing this before. If it works for you let us know in this thread. I could work, it just depends on how it is implemented in the sharing device. If done right, worst case you may get some timeouts but as long as the timeouts did not get to be to numerous it should be fine.  I run a serial over IP device sometimes and it produces less than 1% timeouts (0.9% timeout errors vs total packets sent). Genmon has a thread dedicated to sending modbus request and this thread sends them continiously. You can adjust the modbus timeout in the advanced parameters (double click the gear icon in the upper right web interface).
