### ISSUE TITLE
Estimated Fuel still shown even when accurate fuel amount is available

### ISSUE THREAD

**Issue by lps-rocks** [jgyates/genmon#662]
### Expected Behavior

Estimated Fuel should be disabled when a sensor is detected or plugin is used to monitor fuel source

### Actual Behavior

Estimated Fuel amount remains on maintenance page

### Steps to Reproduce (including precondition)

1. Configure Tank Utility Add-On to pull tank details.
2. Configure total tank size in settings
3. Go to Maintenance page, estimated fuel is still shown despite an accurate number being available.

### Screenshot or Pictures relating to the problem (if possible)

![a0c02413-356c-4f47-a4e8-bbf2421afce7](https://user-images.githubusercontent.com/10893911/152627039-6b0ab87d-0f67-427f-b194-dee7d36b0158.jpg)
![a10dc248-f15c-4c56-bdc2-7b5618073b6e](https://user-images.githubusercontent.com/10893911/152627040-b46b455f-f450-4af7-b1f4-f5c01b807976.jpg)

### Your Environment

- Generator Model: 22kW Home Guardian w/Evo 2 Controller
- Genmon Logs: Submit via the About page
- Genmon Version: V1.18.04

**Comment by jgyates** [comment]
@lps-rocks 

I got your PRs, thanks. 

The fuel estimation can be disable by setting the tank size to zero in the settings. Let me know if that does not solve the issue for you.

For some, like myself who have a diesel tank the built in fuel sensor is accurate most of the time but fuel percentages over 92% and below 10% are not accurate so having both is handy. Have the ability to show both was intentional.

**Comment by lps-rocks** [comment]
Unfortunately, disabling the tank size also makes it stop showing the measured amount as well, it also disables the estimated runtime remaining calculations.

![e9cd11ed-e03b-46df-bfc8-7cc6afcc43ed](https://user-images.githubusercontent.com/10893911/152628601-36611b5d-1557-44b1-84bf-483ab2f0dad6.jpg)

**Comment by jgyates** [comment]
I will look into this. Currently genmon does not use the tank size parameter from tank utility since it already had that data from local settings. I am hesitant to make this change until I can look at it closely as this removes functionality. In the interim, If you want to compensate for a non full tank you can either use a lower tank size or use the "Subtract Fuel" parameter on the settings page.

**Comment by lps-rocks** [comment]
Could we make it an advanced option to disable the display of estimated tank fuel? It does look like the estimated runtime remaining accurately uses the sensor data, so nothing needs to be changed there.

**Comment by lps-rocks** [comment]
I created a PR with the logic I changed on my installation so it functions properly now without having to grab the capacity from tank utility. It looks like tank utility is already grabbing the capacity but just isn't *using* it. 

It may show what I'm trying to do a little bit better.
