### ISSUE TITLE
Repeated power outage notifications when power is still on

### ISSUE THREAD

**Issue by Spuds** [jgyates/genmon#706]
### Expected Behavior

Do not send email notifications (error/warn) when power did not actually drop (0 duration events)

### Actual Behavior

Will get multiple (6-10), quick succession, emails informing of power outage/restore all showing Utility Power Restored. Duration of outage 0:00:00

### Steps to Reproduce (including precondition)

It will be fine for many hours then suddenly you will get 6-10 repeat notices of outage/restored, when there was no such event.  

The only recent change that occurred was our annual service maintance, it still shows the firmware @ 1.09.  I have also been experiencing some short WLAN internet drops in the last few days (LAN is fine but access to Web drops for 10-30 seconds), so don't know if that could be a contributing factor.

### Your Environment

- Generator Model: Evolution 2.0, Air Cooled / 22kW
- Genmon Logs: Submit via the About page (done)
- Genmon Version: V1.18.11

**Comment by jgyates** [comment]
I received you log files. This can be caused by one of two issues.

1) Serial communications failures. You log has the following errors in you /var/log/mymodbus.log file on 5/2/2022:

     2022-05-02 04:11:32,227 : Error: timeout receiving slave packet for register 0056 Buffer: 0, sequence 52768929
     2022-05-02 12:17:58,827 : Error: timeout receiving slave packet for register 0052 Buffer: 0, sequence 53641193

If a timeout occurs (default timeout value is about 3 seconds) and genmon moves on to send the next packet, the controller can send the response to the initial packet which will cause invalid data to be received. This can cause the software to think that conditions are occurring that are not valid, like an outage. Check your cabling and see if this issue still occurs. Unfortunately this is a limit of the modbus protocol (no defined timeout, no way to cancel a response and no way to identify mismatched responses). Another think to try it to increase the modbus timeout value on the advanced settings page (double click the gear icon in the upper right of the web interface to access the settings page). You can add a value of 2 or 3 to the "Additional Modbus Timeout (sec)" setting on this page, then save your settings at the bottom of the page.

2) Since you are using an Evo 2 controller, see number 11 on the known issues list:

     https://github.com/jgyates/genmon/wiki/Appendix-D-Known-Issues

Let me know if you have any other questions.

**Comment by Spuds** [comment]
Thanks for the suggestions

Those communication errors, by date, its when the system was being worked on (annual maintance).  But I've had outage notifications post that date, received 10 in a row this AM.

I'll try tweaking the modbus timeout as well as the disable unknown values setting and see if that clears it up.  I'll check the wires as well, its strange that it was coincident with the maintance.

**Comment by jgyates** [comment]
also, keep an eye on the communication stats on the Monitor page. Mostly look for timeout errors and see if they occur when  you see outage notices.
