### ISSUE TITLE
Finding support for older model 0052440?

### ISSUE THREAD

**Issue by garryadkins** [jgyates/genmon#711]
Use the template below if you have an issue or want to report a bug. If you have a question or a feature request you can ignore the questions below. This is a template so feel free to remove any of this text. Try to include the info below when applicable.

Hi, my 81 year old mom has an 18/16kw generac model from around 2006, model 0052430.  It recently had a battery failure and did not start, creating a bit of a concern for me.... Searching I found genmon!  I can't seem to figure out if it's supported by searching issues here and the wiki.  I'm pretty handy with RPIs and electronics in general so I'm not afraid to connect something up and try it out.

I looked up the model of the controller, and it's 0G5715.   It looks like it has at least 3 header groupings.
Generac manuals are here based on the serial number:  https://www.generac.com/service-support/product-support-lookup/product-manuals?modelNo=4688225

I'll attach pictures of the model plate, controller board and what the user interface looks like.  It's basically just some LEDs and a couple of switches. 

Thanks for any help!

### Your Environment

- Generator Model: 0052430
- Genmon Logs: Submit via the About page
- Genmon Version: {Please write here}
![20220521_174448](https://user-images.githubusercontent.com/86593759/169673793-ef5d59b5-898b-4e38-a1b5-2e6de7570db9.jpg)
![20220521_174459](https://user-images.githubusercontent.com/86593759/169673797-951dce2f-67c0-4ce2-b371-6b14072b4273.jpg)
![s-l400](https://user-images.githubusercontent.com/86593759/169673800-22d9c931-46c5-4cdf-8d67-df0ef9c7b653.jpg)

**Comment by jgyates** [comment]
Hi @garryadkins 

The main requirement for support on this project is the controller must use modbus. The earliest known generac controller for residential use that supports modbus is from 2008. The controller looks like this:

https://raw.githubusercontent.com/jgyates/genmon/master/Diagrams/2008-PreNexusController.jpg

Based on the info provided I would say that this controller is not supported and could not easily be supported since it does not appear to support modbus. this model appears to have an LED based display. 

I recall seeing a small system once that monitored the transfer switch and would allow you to send a simple email if the weekly exercise was not performed. Something like that may work in your case. This project has an add on that would allow you to read the two line currents via two current transformers form the pi. That could be modified to do a simple monitor.

I hope this helps.
