### ISSUE TITLE
Possible Feature Request - Switch to Generator on high utility voltage

### ISSUE THREAD

**Issue by TopBanana123** [jgyates/genmon#749]
I've spent all day researching, and I don't see anything that says the Generac ATS switches on too high of an input voltage

Is there any way to get Genmon to control the generator and switch to generator power if the utility voltage is too high? For example if it's over 130/260v, turn on and switch to generator. And then back again when it calms down

Would be great if it could do the same for a high imbalance of the lines which could indicate a bad neutral at the transformer from the utility

**Comment by jgyates** [comment]
Hi @TopBanana123 

On residential Generac systems, the controller makes the decision to activate the transfer switch (not the ATS) so this feature would not protect the controller since utility voltage is always connected to the controller. In general I am hesitant to create an add on that will enable the transfer switch other than for testing purposes as this could tend to create a hope that this software could be used as a protection device when in reality the software is not directly in control of the timing of the switch activation.  The software can issue command the controller, then the controller will start the generator and  if the start is successful, then activate the transfer switch.  The software can not directly control the ATS. A surge suppressor would be needed to provide any real level protection.

Also, the controller only outputs the combined voltage level. The voltage level of each leg is not exported over modbus. I assume that if one leg was down or dropped as long as the total combined voltage (default is 143V) is below the threshold voltage the generator would consider this an outage and start the generator. If you are concerned about a high imbalance you could raise the threshold voltage from the dealer settings.

I am going to close this issue for now but feel free to post any follow up questions or comments.
