### ISSUE TITLE
Pushover usage question - not genmon problem

### ISSUE THREAD

**Issue by DC072012** [jgyates/genmon#816]
Use the template below if you have an issue or want to report a bug. If you have a question or a feature request you can ignore the questions below. This is a template so feel free to remove any of this text. Try to include the info below when applicable.

***NOTE:*** If you are having issues with your serial connection, please read this page before posting:

https://github.com/jgyates/genmon/wiki/3.6---Serial-Troubleshooting

If you are having other issues, please see the following page:

https://github.com/jgyates/genmon/wiki/3.5---General-Troubleshooting

You can search past issues by removing the "is:open" keywords from the search window and adding any keywords that are relevant to your issue.

If you need to send you logs and registers to the developer, if your email is setup and working properly you can click send your logs on the About page in the web interface.

### Expected Behavior

{Please write here}

### Actual Behavior

I have pushover notifications working via the genmon GUI interface.  Working great.  Now that the pushover framework is installed on the Pi, I’m trying to figure out if / how I can use it outside of genmon.

I have searched this genmon issues forum, and online elsewhere, but I’m not expert enough to figure this out.

For some reason I have sporadic wifi disconnects from the Pi to my router.  The signal level hovers around -50db so signal is good.
On the Pi I have implemented a script based on an adaptation by the one published by Kevin Reed.
Wificheck script is triggered by a cron job every 15 minutes.  

I’d like to add a pushover notification to my wificheck script that will send me a notification that the wificheck script detected a down situation and has attempted a restart of the wifi connection. 

I realize if the wifi connection does not reconnect, I most likely won’t get the notification.  
But if the wifi reconnection is successful I’d like to get notified via pushover so I can investigate the incident further.

I am running on a Pi 3B:
Linux raspberrypi 5.15.74-v7+ #1595 SMP Wed Oct 26 11:03:05 BST 2022 armv7l

Thank you in advance for any help you can provide.

### Steps to Reproduce (including precondition)

{Please write here}

### Screenshot or Pictures relating to the problem (if possible)

{Please write here}

### Your Environment

- Generator Model: 005882 8kw
- Genmon Logs: No errors
- Genmon Version: V1.18.15

**Comment by jgyates** [comment]
Genmon does not have a callable interface for add on (or other programs). You could create a small python program that is called when your script is called. The python code that the genmon add on uses to call the pushover libraries is here:

https://github.com/jgyates/genmon/blob/9e1d9138bcf981c6c6feadfbb7a381817e6d2992/addon/genpushover.py#L202

I also use the check wifi script form Kevin Reed however since it is called from a cron job, I have the linux system setup to send emails when the cron job runs.

https://www.sbprojects.net/projects/raspberrypi/exim4.php

The link above will setup your email to work with your linux system. Once a cronjob is run you will get a notice. With the wifi check script I get an email if the wifi needs to be restarted.

I am going to close this thread but feel free to post any follow up questions here.
