### ISSUE TITLE
Is there a way to automate backups so that all data is backed up weekly to an SMB or SFTP share?

### ISSUE THREAD

**Issue by northportio** [jgyates/genmon#891]
Just got genmon working nicely with my Generac 24 Kw. I entered a bunch of information into the service journal and I saw there's a function to backup the data from what I assume the `/etc/genmon/` directory.

I love Raspberry Pis but I know that sometimes the SD card can fail, or the pi can fail as well as this is sitting outdoors in a "weatherproof-ish" enclosure I made, I'd like to automate the backups to connect to my smb share. 

I can write a bash script and automate that with cron if it's just backing up the `/etc/genmon/` directory. Please tell me if I'm wrong.

Maybe a feature request to automate the backups? Thanks.

**Comment by jgyates** [comment]
The weekly backup to an external location is not supported currently however you can use the genmonmaint.sh script to create a compressed archive and then move the file your with your script.

https://github.com/jgyates/genmon/blob/42613950d0b0979db0e9d036befd62437f58d8a0/genmonmaint.sh#L284

If you run this from the /home/pi/genmon folder is will create a compressed archive file in the same folder.

beyond that is probably outside the scope of the project and there are many ways to do that so I will likley not incorporate the external file share aspect. The only thing you are really getting doing a weekly backup is power and outage logs since the settings do not change once it is setup but if you want that you can just export the archive file mention above.

  genmonmaint.sh -b

**Comment by skipfire** [comment]
@northportio you could have cron run this script daily.

```
from datetime import datetime
import ftplib
import shutil

#Configuration
ftpServer = "myftp"
ftpUser = "myuser"
ftpPassword = "mypass"

backupFileName = "genmon_backup_" + datetime.now().strftime("%Y%m%d")

#Zip the files
shutil.make_archive(backupFileName, 'zip', '/etc/genmon')

#FTP
session = ftplib.FTP(ftpServer, ftpUser, ftpPassword)
file = open('genmonbackup.zip','rb')
session.storbinary('STOR genmonbackup.zip', file)
file.close()
session.quit()
```
