### ISSUE TITLE
Settings screen - Sync Time

### ISSUE THREAD

**Issue by krisasmith** [jgyates/genmon#91]
Use the template below if you have an issue or want to report a bug. If you have a question or a feature request you can ignore the questions below.

### Expected Behavior

The settings screen would show that the 'Sync Time' setting is 'on'.

### Actual Behavior

The 'Sync Time' setting is set to true in the /etc/genmon.conf file

### Steps to Reproduce (including precondition)

n/a

### Screenshot on This Problem (if possible)

![image](https://user-images.githubusercontent.com/27901356/38740683-2bc86a86-3f06-11e8-8a65-cfab0e1a0bac.png)

![image](https://user-images.githubusercontent.com/27901356/38740720-45778dcc-3f06-11e8-8141-d3e3491950f0.png)

### Your Environment

- Genereator Model: {Please write here}
- Generator Registers: {Please write here}
- Genmon Version: {Please write here}

**Comment by jgyates** [comment]
Hi Kris,

I can duplicate this, I think it is related to the UI not updating it settings after Save is clicked. If you go to another page after the Save is complete it does not occur. If you  stay on the Settings page and make a second change, it does not appear to update properly. I will look at this and try to get a fix posted. I *think* this bug is related to the other one your submitted (https://github.com/jgyates/genmon/issues/92).

Thanks
Jason

**Comment by jgyates** [comment]
I checked in a change. This should fix the problem. I am not forcing a page refresh after settings are applied. This is a bit brute force to fix the issue, another update may be coming that is more elegant, but this should fix it.

**Comment by jgyates** [comment]
The cleaner solution is checked in now. No longer forces a refresh but should handle the settings update as expected.
