### ISSUE TITLE
Possible FYI for others if using rpi 3A+

### ISSUE THREAD

**Issue by Schlats** [jgyates/genmon#929]
I've installed genmon earlier this year utilizing a pi 3A+ with rpi os lite bullseye 9-22-22 and genmon 18.16, used in conjunction with home assistant. It was pretty easy once figuring out the install process. Its been successfully working since.
I spent all day working through setting up another genmon setup using another pi 3A+ using rpi os lite. I had so much trouble trying to get genmon to work, it would install but the web gui would not work. I happened to have the old version of rpi os from my first setup, it didn't work either. Considering I couldn't use an older version of genmon, and I started trying other versions of rpi os. For some reason I found the  only way I could get it to work is to use the amd64 lite rpi os. 
So it may be that there is an issue with installing genmon on an rpi with the amdhf version since genmon 18.16, because the first setup I did used amdhf, but now genmon doesn't work with amdhf.
By no means is what I say guaranteed as I barely know what I am doing. If there is an issue hope this is helpful to others as genmon is an awesome piece of work and many thanks to jgyates for building it.

**Comment by jgyates** [comment]
Thanks for the info.

I have seen issues like this before. Unfortunately, in my experience, the behavior changes.  I have seen install issues with both the 32 and 64 bit version, but never at the same time. My best guess is that this is the nature of open source software (thousands of pieces of software, maintained by may people, with little interoperability testing between all the items). Each python library has many other dependancies and each library is hosted on servers with multiple mirrors, not all the mirror servers are updated at the same time; these issues can lead to temporary failures in dependent packages.

The short answer is: if you find that the install is failing on the 32 bit, then try the 64 bit and vice versa.  Or alternately, wait a few days and the issue will likely resolve itself as it is probably due to and issue like the mirror server you are pulling from during the install is out of date and needs to be updated.

On the upside, open source software does tend to get fixed quickly compared to closed source issue.
