### ISSUE TITLE
Feature Request: Brief emails/Txts

### ISSUE THREAD

**Issue by Don331** [jgyates/genmon#962]
I'd like to see a Mod so the email/txts from GenMon are more useful

Attached file genmon1 shows what an exercise looks like on Outlook, 
Attached file genmon2 shows what an exercise look like on iPhone.

![genmon1](https://github.com/jgyates/genmon/assets/93215357/b7d17f97-e30b-4104-819c-312e416c352d)
![genmon2](https://github.com/jgyates/genmon/assets/93215357/bf5ea6cf-0285-47c5-be05-e50f5fb2dd59)

**I think it would more useful if the first line in the messages was the engine state.** _That way you'd know right away what was up,_ and then open the email IF more digging was needed. Date & time doesn't need to be first as email stamps the date and time on each message, so that could go further down the body of the message text.

Overall, thanks again for your work on this. I've had mine for several years now, and have helped many of my friends convert to GenMon. 

Don

**Comment by jgyates** [comment]
Hi @Don331,

The time stamps represent a few different times. The time in the email header is the receiver time set by the receiving email server. The timestamp at the top of the email body is the time the email was sent (based on the timezone of the pi). The time at the bottom of the email body is the time of the pi and generator at the time the condition the email is notifying was detected by the software. Due to queuing, possible email transmission errors and differences in time settings on the sender and receiver, each of these times can be helpful when troubleshooting issues.

The format of the email has evolved over time based on feedback from users and it has not changed in a while so I am a little hesitant to change things without thinking it over. Possibly a better solution is to provide more info on how the email subject is formatted now.

The subject of the email set by genmon will let you know of there is an issue that needs attention, it just may not be obvious as all is will with your generator. Here is a break down of the email subjects lines:

* Generator Notice: SiteName - this means that the state of the generator has changed but an alarm is not present. This can change marks the transition from of several state like cranking, warming up, cooling down, exercising, stopping, stopped, running, etc, to another of the same set of states. This email also has the message ""NOTE: This message is a notice that the state of the generator has changed. The system is not in alarm." near the top immediately after the time stamp. This email is always informational and does not indicate anything is wrong with the generator.
* Generator Alert at SiteName CRITICAL - this means the system is in alarm or warning and needs attention
* Generator Notice: Firmware update at SiteName - the firmware has been updated
* Transfer Switch Changed State Notice at SiteName - Evolution Liquid Cooled only
 * Warning: Fuel Level Low - If a fuel gauge is present or fuel calculation is enabled
 * Outage Notice at SiteName - Power is out
 * Outage Recovery Notice at SiteName - Power is restored

There are a couple other rare emails that could be sent but only in very unusual situations like the software identified an unexpected controller and the power log size is getting too big.

Each of these emails is assigned a category of  warning, informational, error, or outage. You can opt not to received emails of a certain category, for example the "Generator Notice" emails use the informational category. You can change what categories are sent on the Notifications page in the web interface. The categories are:

* outage - outage detection and restoration notices
* warn - an alarm or warning has been detected, fuel low warning
* error - there is an unexpected condition was detected by the software or a fatal software fault has occurred with genmon. These conditions may keep the software from functioning as expected
* info - info about state changes of the generator and firmware updates

The genmon software relies heavily on the controller to indicate that there is a problem via a warning or alarm (the controller monitors a lot of conditions for both alarm and warning). If you get an email that has the subject "Generator Alert" then you need to look into it.

Let me know if you have any other questions or feedback.
